enum ActionTypes {
  SEARCH_VIDEO = "SEARCH_VIDEO",
  SELECT_VIDEO = "SELECT_VIDEO",
  LIST_VIDEOS = "LIST_VIDEOS",
  STORE_COMMENTS = "STORE_COMMENTS",
  APPEND_COMMENTS = "APPEND_COMMENTS",
  LOAD_COMMENTS = "LOAD_COMMENTS",
  LOAD_REPLIES = "LOAD_REPLIES",
}
export default ActionTypes;
